- name: "Run dependency-role: ans-role-config-shell"
  ansible.builtin.include_tasks: run_config_shell_role.yml

- name: "Configure bash prompt"
  ansible.builtin.include_tasks: config_prompt.yml

- name: "Configure bash history"
  ansible.builtin.include_tasks: config_history.yml

